apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJRWGx5ZEdGME9tZG9jRjlwUlVWU1FVSk9kWEZFZUdOWVNrbHlPVFo0ZVU1SGJFcDJjbmh4TldVeVFXOTVVMUU9IgogICAgICAgIH0KICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson
